"""Durable run authority, evidence, replay, and recovery contracts."""

from .adapters import (
    ActiveRunContext,
    RunAuthority,
    compaction_payload,
    permission_denial_payload,
    retry_observation_payload,
    tool_audit_payload,
    turn_outcome_status,
    usage_record_payload,
)
from .kernel import apply_evidence, replay, transition_run
from .models import (
    SCHEMA_VERSION,
    Attempt,
    AttemptStatus,
    Evidence,
    EvidenceType,
    Operation,
    OperationKind,
    OperationStatus,
    RecoveryClassification,
    RecoveryDecision,
    Run,
    RunSnapshot,
    RunStatus,
    Turn,
    canonical_json,
    content_digest,
    new_attempt_id,
    new_evidence_id,
    new_operation_id,
    new_run_id,
    new_turn_id,
)
from .store import (
    ConcurrencyConflictError,
    IdempotencyConflictError,
    IntegrityVerificationError,
    RunStoreError,
    SQLiteRunStore,
)

__all__ = [
    "SCHEMA_VERSION",
    "ActiveRunContext",
    "Attempt",
    "AttemptStatus",
    "ConcurrencyConflictError",
    "Evidence",
    "EvidenceType",
    "IdempotencyConflictError",
    "IntegrityVerificationError",
    "Operation",
    "OperationKind",
    "OperationStatus",
    "RecoveryClassification",
    "RecoveryDecision",
    "Run",
    "RunAuthority",
    "RunSnapshot",
    "RunStatus",
    "RunStoreError",
    "SQLiteRunStore",
    "Turn",
    "apply_evidence",
    "canonical_json",
    "compaction_payload",
    "content_digest",
    "new_attempt_id",
    "new_evidence_id",
    "new_operation_id",
    "new_run_id",
    "new_turn_id",
    "permission_denial_payload",
    "replay",
    "retry_observation_payload",
    "tool_audit_payload",
    "transition_run",
    "turn_outcome_status",
    "usage_record_payload",
]
